services:
  db:
    image: mariadb
    restart: "no" 
    #command: "--default-authentication-plugin=mysql_native_password"
    volumes:
      - db-data:/var/lib/mariadb
    env_file:
      - .env
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DB_NAME}
      MARIADB_USER: ${MARIADB_USER} 
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    ports:
      - "3306:3306"
    # healthcheck:
      # test: ["CMD", "mariadb-admin" ,"ping", "-h", "localhost", "-u$$MARIADB_USER", "-p$$MARIADB_PASSWORD"]
      # interval: 5s
      # timeout: 5s
      # retries: 2
    networks:
      - back-tier

  web:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: "no" 
    environment:
      ENVIRONMENT: dev
      WEB_CONCURRENCY: 1
      CODE_RELOAD: true
      DJANGO_SETTINGS_MODULE: config.settings
    env_file:
      - .env
    volumes:
      - ./roc:/roc
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:80"
    networks:
      - front-tier
      - back-tier

volumes:
  db-data: {}

networks:
  front-tier: {}
  back-tier: {}
