# Generated by Django 5.1.3 on 2024-12-02 12:47

import django.db.models.deletion
import django.utils.timezone
import expenditure_register.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100, verbose_name='ΑΛΕ')),
                ('category', models.CharField(default='ΑΓΟΡΕΣ ΑΓΑΘΩΝ ΚΑΙ ΥΠΗΡΕΣΙΩΝ', max_length=50, verbose_name='Κατηγορία')),
                ('subcategory', models.CharField(choices=[('ΙΔΙΩΤΕΣ', 'ΙΔΙΩΤΕΣ'), ('ΥΠΕΡΩΡΙΕΣ ΔΙΟΙΚΗΤΙΚΩΝ', 'ΥΠΕΡΩΡΙΕΣ ΔΙΟΙΚΗΤΙΚΩΝ'), ('ΜΗ ΛΗΨΗ ΑΔΕΙΑΣ', 'ΜΗ ΛΗΨΗ ΑΔΕΙΑΣ'), ('ΑΠΟΖΗΜΙΩΣΗ ΣΑΒΒΑΤΑ-ΚΥΡΙΑΚΕΣ', 'ΑΠΟΖΗΜΙΩΣΗ ΣΑΒΒΑΤΑ-ΚΥΡΙΑΚΕΣ'), ('ΑΠΟΖΗΜΙΩΣΗ ΣΑΒΒΑΤΑ-ΚΥΡΙΑΚΕΣ (ΙΔΟΧ)', 'ΑΠΟΖΗΜΙΩΣΗ ΣΑΒΒΑΤΑ-ΚΥΡΙΑΚΕΣ (ΙΔΟΧ)'), ('ΥΠΕΡΩΡΙΕΣ', 'ΥΠΕΡΩΡΙΕΣ'), ('ΩΡΟΜΙΣΘΙΟΙ', 'ΩΡΟΜΙΣΘΙΟΙ'), ('ΥΠΕΡΩΡΙΕΣ ΣΕ ΒΟΥΛΕΥΤΙΚΑ, ΠΟΛΙΤΙΚΑ ΓΡΑΦΕΙΑ', 'ΥΠΕΡΩΡΙΕΣ ΣΕ ΒΟΥΛΕΥΤΙΚΑ, ΠΟΛΙΤΙΚΑ ΓΡΑΦΕΙΑ'), ('ΟΔΟΙΠΟΡΙΚΑ', 'ΟΔΟΙΠΟΡΙΚΑ'), ('ΟΔΟΙΠΟΡΙΚΑ ΕΞΩΤΕΡΙΚΟΥ', 'ΟΔΟΙΠΟΡΙΚΑ ΕΞΩΤΕΡΙΚΟΥ'), ('ΕΞΟΔΑ ΜΕΤΑΚΙΝΗΣΗΣ ΜΑΘΗΤΩΝ', 'ΕΞΟΔΑ ΜΕΤΑΚΙΝΗΣΗΣ ΜΑΘΗΤΩΝ'), ('ΗΜΕΡΗΣΙΑ ΑΠΟΖΗΜΙΩΣΗ', 'ΗΜΕΡΗΣΙΑ ΑΠΟΖΗΜΙΩΣΗ'), ('ΕΠΙΤΡΟΠΕΣ ΙΔΟΧ', 'ΕΠΙΤΡΟΠΕΣ ΙΔΟΧ'), ('ΕΠΙΤΡΟΠΕΣ', 'ΕΠΙΤΡΟΠΕΣ'), ('ΤΟΚΟΙ ΑΠΌ ΕΚΤΕΛΕΣΗ ΔΙΚΑΣΤΙΚΩΝ ΑΠΟΦΆΣΕΩΝ', 'ΤΟΚΟΙ ΑΠΌ ΕΚΤΕΛΕΣΗ ΔΙΚΑΣΤΙΚΩΝ ΑΠΟΦΆΣΕΩΝ'), ('ΛΟΙΠΕΣ ΑΠΟΖΗΜΙΩΣΕΙΣ ΣΕ ΕΚΤΕΛΕΣΗ ΔΙΚΑΣΤΙΚΩΝ ΑΠΟΦΑΣΕΩΝ', 'ΛΟΙΠΕΣ ΑΠΟΖΗΜΙΩΣΕΙΣ ΣΕ ΕΚΤΕΛΕΣΗ ΔΙΚΑΣΤΙΚΩΝ ΑΠΟΦΑΣΕΩΝ'), ('ΔΙΚΑΣΤΙΚΑ', 'ΔΙΚΑΣΤΙΚΑ'), ('ΞΕΝΟΓΛΩΣΣΑ', 'ΞΕΝΟΓΛΩΣΣΑ'), ('ΕΞΟΔΑ ΔΙΑΝΥΚΤΕΡΕΥΣΗΣ', 'ΕΞΟΔΑ ΔΙΑΝΥΚΤΕΡΕΥΣΗΣ'), ('ΑΚΟΥΣΤΙΚΑ ΒΑΡΥΚΟΪΑΣ', 'ΑΚΟΥΣΤΙΚΑ ΒΑΡΥΚΟΪΑΣ')], max_length=100, verbose_name='Υποκατηγορία')),
                ('description', models.TextField(blank=True, verbose_name='Περιγραφή')),
            ],
        ),
        migrations.CreateModel(
            name='Debit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Ποσό Δέσμευσης')),
                ('debit_protocol_number', models.CharField(max_length=10, verbose_name='Αριθμός πρωτ. απόφασης ανάληψης υποχρέωσης')),
                ('debit_date', models.DateField(default=django.utils.timezone.now, verbose_name='Ημερομηνία Ανάληψης Υποχρέωσης')),
                ('diavgeia_string', models.CharField(max_length=100, verbose_name='ΑΔΑ')),
                ('diavgeia_date', models.DateField(default=django.utils.timezone.now, verbose_name='Ημερομηνία Ανάρτησης στη Διαύγεια')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenditure_register.account', verbose_name='ΑΛΕ')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol_number', models.CharField(max_length=10, verbose_name='Αριθμός σύμβασης')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Ημερομηνία Ανάρτησης στη Διαύγεια')),
                ('diavgeia_string', models.CharField(max_length=100, verbose_name='ΑΔΑ')),
                ('diavgeia_date', models.DateField(default=django.utils.timezone.now, verbose_name='Ημερομηνία Ανάρτησης στη Διαύγεια')),
                ('debit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenditure_register.debit', verbose_name='Αριθμός απόφασης ανάληψης υποχρέωσης')),
            ],
        ),
        migrations.CreateModel(
            name='ExpenditureRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_type', models.CharField(choices=[('ΚΡΑΤΙΚΟΣ_ΠΡΟΫΠΟΛΟΓΙΣΜΟΣ', 'ΚΡΑΤΙΚΟΣ ΠΡΟΫΠΟΛΟΓΙΣΜΟΣ'), ('ΠΡΟΓΡΑΜΜΑ ΔΗΜΟΣΙΩΝ ΕΠΕΝΔΥΣΕΩΝ', 'ΠΡΟΓΡΑΜΜΑ ΔΗΜΟΣΙΩΝ ΕΠΕΝΔΥΣΕΩΝ')], default='ΚΡΑΤΙΚΟΣ_ΠΡΟΫΠΟΛΟΓΙΣΜΟΣ', max_length=32, verbose_name='Τύπος προϋπολογισμού')),
                ('year', models.PositiveSmallIntegerField(default=2024, verbose_name='Οικονομικό Έτος')),
                ('organization', models.CharField(default='1019', max_length=20, verbose_name='Φορέας')),
                ('special_organization', models.CharField(default='206-9922000', max_length=20, verbose_name='Ειδικός Φορέας')),
            ],
            options={
                'unique_together': {('budget_type', 'year')},
            },
        ),
        migrations.AddField(
            model_name='account',
            name='expenditure_register',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenditure_register.expenditureregister', verbose_name='Μητρώο Δεσμεύσεων'),
        ),
        migrations.CreateModel(
            name='Recall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recall', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Ποσό Ανάκλησης')),
                ('recall_protocol_number', models.CharField(max_length=10, verbose_name='Αριθμός πρωτ. απόφασης ανάκλησης δέσμευσης')),
                ('recall_date', models.DateField(default=django.utils.timezone.now, verbose_name='Ημερομηνία Ανάκλησης')),
                ('diavgeia_string', models.CharField(max_length=100, verbose_name='ΑΔΑ Ανάκλησης')),
                ('diavgeia_date', models.DateField(default=django.utils.timezone.now, verbose_name='Ημερομηνία Ανάρτησης στη Διαύγεια')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenditure_register.account', verbose_name='ΑΛΕ')),
            ],
        ),
        migrations.CreateModel(
            name='RequestForPaymentOrInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owned_to', models.CharField(choices=[('ΤΡΙΤΟΥΣ', 'ΤΡΙΤΟΥΣ'), ('ΓΕΝΙΚΗ ΚΥΒΕΡΝΗΣΗ', 'ΓΕΝΙΚΗ ΚΥΒΕΡΝΗΣΗ')], default='ΤΡΙΤΟΥΣ', max_length=100, verbose_name='Υποχρέωση προς')),
                ('afm', models.CharField(max_length=9, validators=[expenditure_register.validators.validate_afm], verbose_name='Α.Φ.Μ.')),
                ('creditor_is_abroad', models.BooleanField(default=False, verbose_name='Πιστωτής μόνιμα εγκατεστημένος στην αλλοδαπή')),
                ('transaction_is_commercial', models.BooleanField(default=False, verbose_name='Εμπορική Συναλλαγή')),
                ('invoice_series', models.CharField(blank=True, max_length=10, null=True, verbose_name='Σειρά τιμολογίου ή άλλου φορολογικού στοιχείου')),
                ('invoice_number', models.CharField(max_length=10, verbose_name='Αριθμός Τιμολογίου ή άλλου ισοδύναμου εγγράφου')),
                ('invoice_date', models.DateField(default=django.utils.timezone.now, verbose_name='Ημερομηνία έκδοσης τιμολογίου ή ισοδύναμου εγγράφου')),
                ('invoice_created_by_us', models.BooleanField(default=False, verbose_name='Αυτόματη συμπλήρωση υπόλοιπων ημερομηνιών (Μόνο αν το τιμολόγιο εκδόθηκε από το φορέα μας. Ελέγξτε τα αποτελέσματα!)')),
                ('invoice_charge_amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Ποσό τιμολογίου ή ισοδύναμου εγγράφου')),
                ('invoice_reception_date', models.DateField(verbose_name='Ημερομηνία παραλαβής τιμολογίου ή ισοδύναμου εγγράφου')),
                ('service_reception_date', models.DateField(blank=True, null=True, verbose_name='Ημερομηνία παραλαβής αγαθών, υπηρεσιών ή εργασιών (Μόνο για εμπορικές συναλλαγές)')),
                ('service_acceptance_verification_date', models.DateField(blank=True, null=True, verbose_name='Ημερομηνία έγκρισης παραλαβής αγαθών, υπηρεσιών ή εργασιών (Μόνο για εμπορικές συναλλαγές)')),
                ('payment_due_date', models.DateField(verbose_name='Συμβατικός χρόνος πληρωμής')),
                ('obligation_creation_date', models.DateField(verbose_name='Ημερομηνία δημιουργίας υποχρέωσης')),
                ('computed_maturation_start_date', models.DateField(verbose_name='Ημερομηνία έναρξης ωρίμανσης')),
                ('computed_payment_due_date', models.DateField(blank=True, null=True, verbose_name='Ημερομηνία λήξης προθεσμίας υποχρέωσης (Μόνο για εμπορικές συναλλαγές)')),
                ('payment_in_advance', models.BooleanField(default=False, verbose_name='Πληρωμή μέσω Πάγιας Προκαταβολής ή Χρηματικού Εντάλματος Προπληρωμής')),
                ('debit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenditure_register.debit', verbose_name='Αριθμός απόφασης ανάληψης υποχρέωσης')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type_choice', models.CharField(choices=[('ΕΞΟΦΛΗΣΗ', 'ΕΞΟΦΛΗΣΗ'), ('ΑΠΟΡΡΙΨΗ', 'ΑΠΟΡΡΙΨΗ'), ('ΑΚΥΡΩΣΗ', 'ΑΚΥΡΩΣΗ')], default='ΑΠΟΔΟΧΗ', max_length=100, verbose_name='Διαχείριση πληρωμής τιμολογίου ή ισοδύναμου εγγράφου')),
                ('number', models.CharField(max_length=10, verbose_name='Αριθμός παραστατικού')),
                ('document_type', models.CharField(choices=[('ΤΑΚΤΙΚΟ ΧΡΗΜΑΤΙΚΟ ΕΝΤΑΛΜΑ', 'ΤΑΚΤΙΚΟ ΧΡΗΜΑΤΙΚΟ ΕΝΤΑΛΜΑ'), ('ΧΡΗΜΑΤΙΚΟ ΕΝΤΑΛΜΑ ΠΡΟΠΛΗΡΩΜΗΣ', 'ΧΡΗΜΑΤΙΚΟ ΕΝΤΑΛΜΑ ΠΡΟΠΛΗΡΩΜΗΣ'), ('ΕΝΤΟΛΗ ΜΕΤΑΦΟΡΑΣ', 'ΕΝΤΟΛΗ ΜΕΤΑΦΟΡΑΣ'), ('ΣΥΜΨΗΦΙΣΤΙΚΟ ΕΝΤΑΛΜΑ', 'ΣΥΜΨΗΦΙΣΤΙΚΟ ΕΝΤΑΛΜΑ'), ('ΣΥΜΨΗΦΙΣΤΙΚΟ ΕΝΤΑΛΜΑ ΣΥΝΕΠΕΙΑ ΚΑΤΑΣΧΕΣΕΩΝ', 'ΣΥΜΨΗΦΙΣΤΙΚΟ ΕΝΤΑΛΜΑ ΣΥΝΕΠΕΙΑ ΚΑΤΑΣΧΕΣΕΩΝ'), ('ΑΚΥΡΩΤΙΚΟ ΕΝΤΑΛΜΑ', 'ΑΚΥΡΩΤΙΚΟ ΕΝΤΑΛΜΑ')], default='', max_length=100, verbose_name='Είδος παραστατικού')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Ημερομηνία παραστατικού (Απόρριψη/Ακύρωση/Εξόφληση)')),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Συνολικό ποσό πληρωμής')),
                ('payment_amount_to_third_persons', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Συνολικό ποσό πληρωμής ληξιπρόθεσμων οφειλών > 90 ημερών προς τρίτους')),
                ('setoff_payment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Εκ του οποίου συμψηφισμοί/παρακράτηση υπέρ Δημοσίου ή ΟΚΑ')),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='expenditure_register.requestforpaymentorinvoice', verbose_name='Τιμολόγιο')),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Ποσό Μεταφοράς')),
                ('protocol', models.CharField(max_length=10, verbose_name='Αριθμός Πρωτοκόλλου')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Ημερομηνία Μεταφοράς')),
                ('diavgeia_string', models.CharField(blank=True, max_length=100, null=True, verbose_name='ΑΔΑ')),
                ('diavgeia_date', models.DateField(default=django.utils.timezone.now, verbose_name='Ημερομηνία Ανάρτησης στη Διαύγεια')),
                ('expenditure_register', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='expenditure_register.expenditureregister', verbose_name='Μητρώο Δεσμεύσεων')),
                ('incoming_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_accout', to='expenditure_register.account', verbose_name='Μεταφορά σε ΑΛΕ')),
                ('outgoing_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_accout', to='expenditure_register.account', verbose_name='Μεταφορά από ΑΛΕ')),
            ],
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_reform', models.CharField(choices=[('ΕΓΚΕΚΡΙΜΕΝΗ', 'ΕΓΚΕΚΡΙΜΕΝΗ'), ('ΑΝΑΜΟΡΦΩΣΗ', 'ΑΝΑΜΟΡΦΩΣΗ')], default='ΑΝΑΜΟΡΦΩΣΗ', max_length=100, verbose_name='Τύπος Πίστωσης')),
                ('credit', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Ποσό Πίστωσης')),
                ('disposed_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Ποσοστό Διάθεσης')),
                ('date_of_disposal', models.DateField(default=django.utils.timezone.now, verbose_name='Ημερομηνία Πίστωσης')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenditure_register.account', verbose_name='ΑΛΕ')),
                ('transfer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='expenditure_register.transfer', verbose_name='Μεταφορά')),
            ],
        ),
    ]
