# Generated by Django 5.1.3 on 2024-12-03 07:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenditure_register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Ποσό Μεταφοράς')),
                ('protocol', models.CharField(max_length=10, verbose_name='Αριθμός Πρωτοκόλλου')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Ημερομηνία Μεταφοράς')),
                ('diavgeia_string', models.CharField(blank=True, max_length=100, null=True, verbose_name='ΑΔΑ')),
                ('diavgeia_date', models.DateField(default=django.utils.timezone.now, verbose_name='Ημερομηνία Ανάρτησης στη Διαύγεια')),
                ('expenditure_register', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='expenditure_register.expenditureregister', verbose_name='Μητρώο Δεσμεύσεων')),
                ('incoming_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_accout', to='expenditure_register.account', verbose_name='Μεταφορά σε ΑΛΕ')),
                ('outgoing_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_accout', to='expenditure_register.account', verbose_name='Μεταφορά από ΑΛΕ')),
            ],
        ),
        migrations.AddField(
            model_name='credit',
            name='transfer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_accout', to='expenditure_register.transfer', verbose_name='Μεταφορά'),
        ),
        
    ]
