# Generated by Django 5.1.3 on 2024-11-28 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenditure_register', '0002_alter_credit_credit_reform_alter_credit_transfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='transfer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='expenditure_register.transfer', verbose_name='Μεταφορά'),
        ),
    ]
