# Generated by Django 4.0.5 on 2023-01-11 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenditure_register', '0040_alter_account_subcategory_alter_credit_credit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='number',
            field=models.CharField(max_length=100, verbose_name='ΑΛΕ'),
        ),
        migrations.AlterField(
            model_name='expenditureregister',
            name='year',
            field=models.PositiveSmallIntegerField(default=2023, verbose_name='Οικονομικό Έτος'),
        ),
    ]
