"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""
import os
from environs import Env
from pathlib import Path
import sentry_sdk
import decimal
dc = decimal.DefaultContext
dc.prec = 20
# print(dc)

# --- gstam ---
env = Env()
env.read_env("../.env", recurse=False)
SECRET_KEY = env('SECRET_KEY')
DEVELOPMENT = env('DEVELOPMENT')

sentry_sdk.init(
    dsn= env('DSN'),
    # Set traces_sample_rate to 1.0 to capture 100%
    # of transactions for performance monitoring.
    # We recommend adjusting this value in production.
    traces_sample_rate=.1,
    # Set profiles_sample_rate to 1.0 to profile 100%
    # of sampled transactions.
    # We recommend adjusting this value in production.
    profiles_sample_rate=0.1,
    environment="development",
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

if DEVELOPMENT:
    DEBUG = True
    ALLOWED_HOSTS = ['*']
    CSRF_TRUSTED_ORIGINS = ['http://192.168.2.217:8000', 'http://139.91.68.114:8000']
else:
    DEBUG = False
    # SECURITY WARNING: don't run with debug turned on in production!
    ALLOWED_HOSTS = ['roc.dide.ira.net', 'roc.dideira.gr']
    # CSRF_COOKIE_SECURE = False
    CSRF_TRUSTED_ORIGINS = ['http://roc.dide.ira.net', 'https://roc.dideira.gr', 'https://roc.dideira.gr']

# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': env('MARIADB_DATABASE'), 
        'USER': env('MARIADB_USER'),
        'PASSWORD': env('MARIADB_PASSWORD'),
        'HOST': env('MARIADB_HOST_IP'),
        'PORT': env('MARIADB_PORT'),
        }
    }
# *** gstam *** END



INSTALLED_APPS = [
    'expenditure_register.apps.ExpenditureRegisterConfig',
    'crispy_forms',
    'crispy_bootstrap5',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# django-crispy-forms
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"


LOGIN_REDIRECT_URL = '/expenditure_register/register/list'
LOGOUT_REDIRECT_URL = '/expenditure_register/' #/accounts/login'
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

USE_L10N = True
USE_I18N = True
USE_TZ = True

LANGUAGE_CODE = 'el-GR' #'en-us'
LOCALE = 'el_gr@euro'
TIME_ZONE = 'Europe/Athens'

THOUSAND_SEPARATOR = '.'
DECIMAL_SEPARATOR = ','
NUMBER_GROUPING = 3
USE_THOUSAND_SEPARATOR = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = '/roc/static_files/'
MEDIA_ROOT = '/roc/media_files/'
# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
